import sqlite3
conexion = sqlite3.connect('instance/time_tracking.db')
cursor = conexion.cursor()
cursor.execute('INSERT INTO user (id, username) VALUES (?, ?)', (1, 'FRODRIGUEZ'))
cursor.execute('INSERT INTO user (id, username) VALUES (?, ?)', (2, 'FPULIDO'))
cursor.execute('INSERT INTO user (id, username) VALUES (?, ?)', (3, 'LGONZALEZ'))
cursor.execute('INSERT INTO user (id, username) VALUES (?, ?)', (4, 'JRONDON'))
conexion.commit()
cursor.close()
conexion.close()